version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: dbuser

  web:
    restart: always
    build: .
    command: ./scripts/docker-entrypoint-django.sh

    depends_on:
      - postgres
    ports:
      - ":8000"
    volumes:
      - static:/www
    env_file: .dev.env

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "8084:80"
    volumes:
      - static:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
  static:
  postgres_data:
