# Generated by Django 5.1.6 on 2025-02-08 13:45

from django.db import migrations, models


def create_default_doors(apps, schema_editor):
    Door = apps.get_model('smwApp', 'Door')
    Door.objects.create()


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("smwApp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_doors),
    ]
