# Generated by Django 5.1.6 on 2025-02-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwApp', '0002_create_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
